version: 3.0.0.{build}-beta
image: Visual Studio 2017
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
environment:
    ANDROID_HOME: "C:\\android-sdk-windows"
init:
  - mkdir %ANDROID_HOME%"
  - cd "%ANDROID_HOME%"
  - appveyor DownloadFile "https://dl.google.com/android/repository/tools_r25.2.5-windows.zip"
  - 7z x "tools_r25.2.5-windows.zip" > nul
  - cd "C:\projects\settingsplugin"
install: 
  - echo y | "%ANDROID_HOME%\tools\android.bat" update sdk -u -a -t tools
  - echo y | "%ANDROID_HOME%\tools\android.bat" update sdk -u -a -t platform-tools
  - echo y | "%ANDROID_HOME%\tools\android.bat" update sdk -u -a -t build-tools-25.0.6
  - echo y | "%ANDROID_HOME%\tools\android.bat" update sdk -u -a -t android-25
  - echo y | "%ANDROID_HOME%\tools\android.bat" update sdk -u -a -t android-15
build_script:
- cmd: >-
    powershell .\bootstrapper.ps1 -Target Default -Verbosity diagnostic
artifacts:
- path: ./Build/nuget/*.nupkg
  name: NuGet
